### ISSUE TITLE
Use of reserved property name "severity"

### ISSUE THREAD

**Issue by Vasileios-Mavroeidis** [fovea-research/stix2.1-coa-playbook-extension#2]
According to the STIX 2.1 specification, Section 3.8, the property name "severity" is reserved and thus it should not be used.

The nested property extension defined in this repo for the COA SDO to support playbook sharing utilizes the property "severity". This needs to be renamed.

The easiest solution is to change the property "severity" to playbook_severity. Similarly, to stay consistent with how we name properties I suggest changing "priority" and" impact" to "playbook_priority" and "playbook_impact".

**Comment by mateusdz** [comment]
Ok, I will update it both in readme and code.

**Comment by mateusdz** [comment]
Updated.
